# Generated by Django 4.2.5 on 2025-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_forgotpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='otp',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
